version: '3.9'

services:
  db:
    image: fredyuniputumayo/db_prueba:1.0   
    container_name: db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: "municipios"
    volumes:
      - ./persistencia:/var/lib/mysql 
    networks:
      - wpsite

  web:
    image: fredyuniputumayo/web_prueba:1.0
    container_name: web
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: "app.py"
      FLASK_ENV: "development"
      MYSQL_HOST: "db"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "1234"
      MYSQL_DB: "municipios"
    depends_on:
      - db
    networks:
      - wpsite

  phpmyadmin:
    image: fredyuniputumayo/phpmyadmin_prueba:1.0
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: "db"
      PMA_USER: "root"
      PMA_PASSWORD: "1234"
    networks:
      - wpsite

networks:
  wpsite:

volumes:
  persistencia:
 